# Generated by Django 5.2.13 on 2026-04-26 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        ('microdrama', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbatch',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_batches', to='microdrama.chapter'),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uploadbatchfile',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='media.uploadbatch'),
        ),
    ]
