# Generated by Django 5.2.13 on 2026-04-26 17:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='This should always be a camelCase string.', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Key must be a camelCase string.', regex='^[a-z]+(?:[A-Z][a-z0-9]*)*$')])),
                ('active', models.BooleanField(default=False)),
                ('value', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(1, 'Boolean'), (2, 'String'), (3, 'Integer')], help_text='The data type of the feature flag used by the serializer.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(help_text='Permissions associated with this feature', to='auth.permission')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'permissions': [('can_develop_features', 'Can develop features (developer)'), ('can_alpha_test_features', 'Can alpha test features'), ('can_beta_test_features', 'Can beta test features')],
            },
        ),
    ]
