# Generated by Django 5.2.13 on 2026-04-26 17:13

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Custom name for the referral link", max_length=255
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=500)),
                ("cta_text", models.CharField(default="Learn More", max_length=100)),
                (
                    "link_type",
                    models.CharField(
                        choices=[("unique", "Unique"), ("shared", "Shared")],
                        default="shared",
                        max_length=10,
                    ),
                ),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("click_count", models.PositiveIntegerField(default=0)),
                ("enabled", models.BooleanField(default=True)),
                ("assigned_email", models.EmailField(blank=True, max_length=254)),
                (
                    "deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the referral link is soft deleted",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReferralClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anonymous_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        help_text="UUID from the mvb_anon_id cookie. Persists across login.",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        help_text="Django session key at click time — secondary correlation.",
                        max_length=40,
                    ),
                ),
                (
                    "is_new_user",
                    models.BooleanField(
                        blank=True,
                        help_text="True if the attributed user registered after this click.",
                        null=True,
                    ),
                ),
                (
                    "attributed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the click was matched to a logged-in user.",
                        null=True,
                    ),
                ),
                ("clicked_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referral_clicks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-clicked_at"],
            },
        ),
    ]
