# Generated by Django 5.2.13 on 2026-04-26 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shortlink", "0001_initial"),
        ("shows", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="referrallink",
            name="show",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referral_links",
                to="shows.show",
            ),
        ),
        migrations.AddField(
            model_name="referralclick",
            name="referral_link",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clicks",
                to="shortlink.referrallink",
            ),
        ),
    ]
