name: MovBits - Remote
values:
  - key: base_url
    value: ''
    enabled: true
  - key: username
    value: ''
    enabled: true
  - key: access_token
    value: ''
    enabled: true
  - key: refresh_token
    value: ''
    enabled: true
  - key: team_uuid
    value: ''
    enabled: true
color: 240
