[pytest]
DJANGO_SETTINGS_MODULE = movbitsapi.settings.base
python_files = tests.py test_*.py *_tests.py
pythonpath = src
filterwarnings =
    ignore:app_settings\.USERNAME_REQUIRED is deprecated:UserWarning:dj_rest_auth.registration.serializers
    ignore:app_settings\.EMAIL_REQUIRED is deprecated:UserWarning:dj_rest_auth.registration.serializers
