# Generated by Django 5.2.13 on 2026-04-26 17:13

import django.db.models.deletion
import microdrama.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('ctype', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(default=10)),
                ('data', models.JSONField(blank=True, default=microdrama.models.episode_data_default, null=True)),
                ('order', models.IntegerField(default=0, help_text='Episode number in the series')),
                ('active', models.BooleanField(default=True, help_text='Is this episode active?')),
                ('chapter_count', models.IntegerField(default=0, help_text='Number of active chapters')),
            ],
        ),
        migrations.CreateModel(
            name='SeriesMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.IntegerField(choices=[(1, 'Hidden Gems'), (2, 'Hero Section'), (3, 'Must See'), (4, 'Trending')])),
                ('order', models.IntegerField(default=0, help_text='Order for display (lower comes first)')),
            ],
            options={
                'verbose_name': 'Series Marketing',
                'verbose_name_plural': 'Series Marketing',
            },
        ),
        migrations.CreateModel(
            name='SeriesStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Series Stats',
                'verbose_name_plural': 'Series Stats',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order', models.IntegerField(default=0, help_text='Order in the playlist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('chapter_number', models.IntegerField(help_text='Chapter number in the episode')),
                ('video_url', models.CharField(blank=True, null=True)),
                ('cdn', models.IntegerField(choices=[(1, 'Vimeo'), (2, 'YouTube'), (3, 'Amazon S3 Media Bucket')])),
                ('active', models.BooleanField(default=True, help_text='Is this chapter active?')),
                ('free', models.BooleanField(default=False, help_text='Is this chapter free to watch?')),
                ('transcoded', models.BooleanField(default=False, help_text='Has the video been transcoded and is ready to watch?')),
                ('src_video', models.FileField(blank=True, help_text='Source video file for transcoding', null=True, upload_to=microdrama.models.chapter_video_upload_path)),
                ('playlist_text', models.TextField(blank=True, help_text='Raw HLS playlist content', null=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='microdrama.episode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LibraryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_id', models.IntegerField(blank=True, help_text='Referral ID associated with this entry', null=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='microdrama.episode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Library Entry',
                'verbose_name_plural': 'Library Entries',
            },
        ),
        migrations.CreateModel(
            name='ChapterView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'Locked (not watched)'), (1, 'Free and unwatched'), (2, 'Free and watched'), (3, 'Paid and unwatched'), (4, 'Paid and watched'), (5, 'In progress')], default=0)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('watched_at', models.DateTimeField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='microdrama.chapter')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_views', to='microdrama.libraryentry')),
            ],
            options={
                'verbose_name': 'Chapter View',
                'verbose_name_plural': 'Chapter Views',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='microdrama.collection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('min_age', models.IntegerField(default=0, help_text='Minimum age to watch the series')),
                ('poster', models.ImageField(blank=True, null=True, upload_to=microdrama.models.series_poster_upload_path)),
                ('active', models.BooleanField(default=True, help_text='Is this series active?')),
                ('episode_count', models.IntegerField(default=0, help_text='Number of active episodes')),
                ('sites', models.ManyToManyField(blank=True, help_text='Select which sites this series is available on', related_name='microdrama_series', to='sites.site')),
            ],
            options={
                'verbose_name': 'Series',
                'verbose_name_plural': 'Series',
                'ordering': ['title'],
            },
        ),
    ]
