# Generated by Django 5.2.13 on 2026-04-26 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('microdrama', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microdramas', to='team.team'),
        ),
        migrations.AddField(
            model_name='episode',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='microdrama.series'),
        ),
        migrations.AddField(
            model_name='seriesmarketing',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing', to='microdrama.series'),
        ),
        migrations.AddField(
            model_name='seriesmarketing',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_marketing', to='sites.site'),
        ),
        migrations.AddField(
            model_name='seriesstats',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='microdrama.series'),
        ),
        migrations.AddField(
            model_name='seriesstats',
            name='site',
            field=models.ForeignKey(help_text='Select which site these stats apply to', on_delete=django.db.models.deletion.CASCADE, related_name='microdrama_series_stats', related_query_name='series_stats', to='sites.site'),
        ),
        migrations.AddField(
            model_name='video',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='microdrama.playlist'),
        ),
        migrations.AlterUniqueTogether(
            name='libraryentry',
            unique_together={('user', 'episode')},
        ),
        migrations.AlterUniqueTogether(
            name='chapterview',
            unique_together={('library', 'chapter')},
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('series', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='seriesmarketing',
            unique_together={('site', 'placement', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='seriesstats',
            unique_together={('series', 'site')},
        ),
    ]
