# Generated by Django 5.2.13 on 2026-04-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(blank=True, null=True)),
                ('group', models.CharField(max_length=255)),
                ('time_block', models.CharField(max_length=16)),
                ('statistics', models.JSONField(default=dict)),
                ('log_data', models.JSONField(default=list)),
            ],
        ),
    ]
