# Generated by Django 5.2.13 on 2026-04-26 17:13

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(editable=False)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "poster_file",
                    models.ImageField(
                        blank=True,
                        help_text="the original poster image file, others are derrived",
                        null=True,
                        upload_to="",
                    ),
                ),
                (
                    "poster_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the poster image, derrived from the file upload",
                        null=True,
                    ),
                ),
                (
                    "banner_file",
                    models.ImageField(
                        blank=True,
                        help_text="the original banner image file, others are derrived",
                        null=True,
                        upload_to="",
                    ),
                ),
                (
                    "banner_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the banner image, derrived from the file upload",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=1, help_text="Order within the show's season"
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        default=0,
                        help_text="Duration in seconds based on sum of videos attached",
                    ),
                ),
                (
                    "rating_value",
                    models.IntegerField(
                        blank=True,
                        help_text="Average user rating from 0 to 50, converted to 0.0 to 5.0",
                        null=True,
                    ),
                ),
                (
                    "rating_count",
                    models.IntegerField(
                        default=0, help_text="Number of user ratings for this episode"
                    ),
                ),
                (
                    "chapter_count",
                    models.IntegerField(
                        default=0, help_text="Number of videos/chapters in this episode"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(editable=False)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "poster_file",
                    models.ImageField(
                        blank=True,
                        help_text="the original poster image file, others are derrived",
                        null=True,
                        upload_to="",
                    ),
                ),
                (
                    "poster_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the poster image, derrived from the file upload",
                        null=True,
                    ),
                ),
                (
                    "banner_file",
                    models.ImageField(
                        blank=True,
                        help_text="the original banner image file, others are derrived",
                        null=True,
                        upload_to="",
                    ),
                ),
                (
                    "banner_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the banner image, derrived from the file upload",
                        null=True,
                    ),
                ),
                ("order", models.IntegerField(default=1)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "tagtype",
                    models.IntegerField(
                        choices=[(1, "General"), (2, "Genre"), (3, "Call-Out")],
                        default=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(editable=False)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "poster_file",
                    models.ImageField(
                        blank=True,
                        help_text="the original poster image file, others are derrived",
                        null=True,
                        upload_to="",
                    ),
                ),
                (
                    "poster_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the poster image, derrived from the file upload",
                        null=True,
                    ),
                ),
                (
                    "banner_file",
                    models.ImageField(
                        blank=True,
                        help_text="the original banner image file, others are derrived",
                        null=True,
                        upload_to="",
                    ),
                ),
                (
                    "banner_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the banner image, derrived from the file upload",
                        null=True,
                    ),
                ),
                (
                    "video_key",
                    models.CharField(
                        blank=True,
                        help_text="The key or ID for the video in the CDN",
                        null=True,
                    ),
                ),
                (
                    "cdn",
                    models.IntegerField(
                        choices=[(1, "Vimeo"), (2, "YouTube"), (3, "Amazon S3 Bucket")]
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        blank=True,
                        help_text="Optional JSON field to store meta data like clip information for the HLS playlist.",
                        null=True,
                    ),
                ),
                ("price", models.IntegerField(default=0)),
                (
                    "duration",
                    models.IntegerField(default=0, help_text="Duration in seconds"),
                ),
                (
                    "rating_value",
                    models.IntegerField(
                        blank=True,
                        help_text="Average user rating from 0 to 50, converted to 0.0 to 5.0",
                        null=True,
                    ),
                ),
                (
                    "rating_count",
                    models.IntegerField(
                        default=0, help_text="Number of user ratings for this episode"
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1,
                        help_text="Version of the video, used for updating the video and generating new signed URLs",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VideoRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(0, "Dislike"), (1, "Neutral"), (2, "Like")], default=1
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="VideoReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                (
                    "watch_started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the user first pressed play. NULL means purchased but not yet watched. The access window (expiration_date) is set from this timestamp.",
                        null=True,
                    ),
                ),
                (
                    "expiration_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Access expires at this time. NULL means the watch window has not started yet (purchased but unwatched). Set to watch_started_at + VIDEO_ACCESS_WINDOW_HOURS on first play.",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Watchlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EpisodeVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=1)),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shows.episode"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="RevShareDeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creator_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.70"),
                        help_text="Fraction of gross revenue paid to the creator (0.70 = 70 %).",
                        max_digits=5,
                    ),
                ),
                (
                    "effective_from",
                    models.DateTimeField(help_text="When this rate came into effect."),
                ),
                (
                    "effective_to",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this rate ended. NULL means this is the currently active deal.",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Platform user who created or approved this deal.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_from"],
            },
        ),
        migrations.AddField(
            model_name="episode",
            name="season",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional Item for a Show with seasons.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shows.season",
            ),
        ),
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(editable=False)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "poster_file",
                    models.ImageField(
                        blank=True,
                        help_text="the original poster image file, others are derrived",
                        null=True,
                        upload_to="",
                    ),
                ),
                (
                    "poster_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the poster image, derrived from the file upload",
                        null=True,
                    ),
                ),
                (
                    "banner_file",
                    models.ImageField(
                        blank=True,
                        help_text="the original banner image file, others are derrived",
                        null=True,
                        upload_to="",
                    ),
                ),
                (
                    "banner_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the banner image, derrived from the file upload",
                        null=True,
                    ),
                ),
                (
                    "series",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the show is a series with multiple episodes",
                    ),
                ),
                (
                    "rating_value",
                    models.IntegerField(
                        blank=True,
                        help_text="Average user rating from 0 to 50, converted to 0.0 to 5.0",
                        null=True,
                    ),
                ),
                (
                    "rating_count",
                    models.IntegerField(
                        default=0, help_text="Number of user ratings for this show"
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shows",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
